# SPDX-License-Identifier: MIT
# statusbar loop
while true; do
    BAT=`cat /sys/class/power_supply/BAT0/capacity`
    xsetroot -name "$(date +"%a %b %d %Y | %R:%S | $BAT%")"
    sleep 1
done &

# start authentication agent
/usr/bin/lxqt-policykit-agent &

# start dunst notification daemon
/usr/bin/dunst &

xwallpaper --maximize "$XDG_CONFIG_HOME/wall.png" &

# start fcitx input method
export GTK_IM_MODULE=fcitx5
export QT_IM_MODULE=fcitx5
export XMODIFIERS=@im=fcitx5
fcitx5 &

# xbindkeys for keyboard shortcuts
xbindkeys --file "$XDG_CONFIG_HOME"/xbindkeys/config &

exec dwm

