" SPDX-License-Identifier: MIT
set number
set relativenumber
set linebreak " break line on word
set showbreak=+++
set textwidth=80
set showmatch " match brace
set hlsearch
set ignorecase
set incsearch " highlight search result while typing
set autoindent
set shiftwidth=8
set tabstop=8
set softtabstop=8
set undolevels=1000
set cc=80 " set colorcolumnn=80
set clipboard=unnamed
set clipboard=unnamedplus
nnoremap <C-\>	:NERDTreeToggle<CR>
nnoremap <leader>n :NERDTreeFocus<CR>
let g:ftplugin_sql_omni_key = '<C-j>'
