" SPDX-License-Identifier: MIT
set number
set relativenumber
set linebreak " break line on word
set showbreak=+++
set textwidth=80
set showmatch " match brace
set hlsearch
set ignorecase
set incsearch " highlight search result while typing
set autoindent
set shiftwidth=8
set tabstop=8
set softtabstop=8
set undolevels=1000
set cc=80 " set colorcolumnn=80
set clipboard=unnamed
set clipboard=unnamedplus
set guioptions -=T
set autoread
syntax on
colorscheme onehalfdark
" normal non-recursive map
nnoremap <C-\>	:Fern . -drawer -right -toggle -width=50<CR>
nnoremap <C-p>	:FZF<CR>
nnoremap <C-t>	:terminal<CR>
nnoremap <C-j>	:tabn<CR>
nnoremap <C-k>	:tabp<CR>
nnoremap <C-t>	:tab terminal<CR>
" https://wiki.archlinux.org/title/XDG_Base_Directory
set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')
set viewdir=$XDG_DATA_HOME/vim/view | call mkdir(&viewdir, 'p')

set backupdir=$XDG_CACHE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_CACHE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_CACHE_HOME/vim/undo     | call mkdir(&undodir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif
