# Version Control System
alias glog="git log --oneline"
alias gs="git status -s" # short status
alias gdiff="git diff"
alias gd="git add ."
alias gp="git push"
alias gcommit="git commit -S"
alias gswitch="git switch"

# Increase Productivity
alias hclear="history -c && history -w"
alias hshow="history"
alias e="nvim"
alias cclip="xclip -sel clip"
alias backup="~/Archived/backup.sh"

# Navigate
alias documents='cd `xdg-user-dir DOCUMENTS`'
alias downloads='cd `xdg-user-dir DOWNLOAD`'
alias videos='cd `xdg-user-dir VIDEOS`'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

# Security
alias scrm="shred -uvz -n 5 "
alias ssuspend="slock & sleep 1 & sudo pm-suspend"

# XDG Base Directory
alias wget="wget --hsts-file="$XDG_CACHE_HOME/wget-hsts""
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/yarnrc"

